### ISSUE TITLE
Initial version

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-cgmes-gl#1]
powsybl-cgmes-gl is a multi-module Mave project with 2 modules:
   - cgmes-gl-conversion: taken from powsybl-incubator. This module is responsible for importing and exporting GL profile.

      package: com.powsybl.cgmes.gl.conversion
      artifactId: powsybl-cgmes-gl-conversion 

   - cgmes-gl-server:  This REST web service should allow the following features:
      - [HIGH PRIORITY] import CGMES-GL coming from a case-server to a geo-data-server: A full CGMES pack (EQ, ..., GL) will be loaded from a case-server, converter to IIDM + position extensions using first cgmes-dl-conversion module and then converted to json and uploaded to a geo-data-server (for both substations and lines).

      REST API
      POST /v1/cases/{caseName}/to-geo-data&countries=FR,BE
      filtering by countries is optional, if no filtering the full network is used. 

      - [LOW PRIORITY => LATER] being able add a GL profile to an existing CGMES zip using data from a geo-data-server. The use case is for instance data coming from Open Data Reseaux Energies and stored in geo-data-server, that we would like to convert to CGMES GL. In that case a CGMES will be selected and loaded from the case store, geo data from the corresponding countries are loaded from the geo-data-server converter to IIDM extensions and converted to CGMES-GL, added to zip and zip updated in the case-server. 

      package: com.powsybl.cgmes.gl.server
      artifactId: powsybl-cgmes-gl-server

**Comment by ChamseddineBhd** [comment]
@geofjamg 
> A full CGMES pack (EQ, ..., GL) will be loaded from a case-server, converter to IIDM + position extensions :  

I think it's heavy to load a full cgmes pack (EQ, ..., GL) from the case server to just extract geographic data ! why do not  process the operation in the case server side ? we can trigger it using the cgmes gl server so we gain in performance ?
